<script setup lang="ts">
import { useIridis } from '~/composables/useIridis.ts';

/**
 * iridis × Nuxt UI demo. Every color on this page is generated by the iridis
 * engine from the seeds below. Sections demonstrate additive palettes, image
 * extraction, role resolution + contrast, color-space conversion, and
 * multi-target output — all re-theming the Nuxt UI components live.
 */
useIridis(); // boot the shared engine store for the page
</script>

<template>
  <UContainer class="space-y-8 py-10">
    <header class="space-y-2">
      <h1 class="text-4xl font-bold text-highlighted">iridis × Nuxt UI</h1>
      <p class="max-w-2xl text-muted">
        Every token on this page — buttons, borders, code, badges — is produced by
        <code>engine.run()</code>. Edit the seeds, drop in an image, or switch schemas and the whole
        Nuxt UI surface re-tones live.
      </p>
    </header>

    <div class="grid gap-6 lg:grid-cols-2">
      <PalettePlayground />
      <ImageExtractor />
    </div>

    <section class="space-y-4">
      <h2 class="text-lg font-semibold text-highlighted">Live component surface</h2>
      <UCard>
        <div class="space-y-5">
          <div class="flex flex-wrap gap-2">
            <UButton color="primary">Primary</UButton>
            <UButton color="primary" variant="outline">Outline</UButton>
            <UButton color="primary" variant="soft">Soft</UButton>
            <UButton color="secondary">Secondary</UButton>
            <UButton color="success">Success</UButton>
            <UButton color="warning">Warning</UButton>
            <UButton color="error">Error</UButton>
            <UButton color="info">Info</UButton>
            <UButton color="neutral" variant="outline">Neutral</UButton>
          </div>
          <div class="grid gap-4 sm:grid-cols-2">
            <div class="space-y-3">
              <UInput placeholder="Search…" icon="i-lucide-search" />
              <USlider :default-value="60" />
              <UProgress :model-value="72" />
              <div class="flex gap-2">
                <UBadge color="primary">primary</UBadge>
                <UBadge color="success" variant="soft">success</UBadge>
                <UBadge color="warning" variant="soft">warning</UBadge>
                <UBadge color="error" variant="outline">error</UBadge>
              </div>
            </div>
            <UAlert
              color="primary"
              variant="soft"
              title="Themed by the engine"
              description="This alert, its icon, border, and text all read from --ui-* variables the projector wrote."
              icon="i-lucide-palette"
            />
          </div>
        </div>
      </UCard>
    </section>

    <ResolvedRoles />

    <div class="grid gap-6 lg:grid-cols-2">
      <ColorSpaces />
      <MultiOutput />
    </div>
  </UContainer>
</template>
