<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import { applyIridisTheme } from '~/theme/iridisProjector.ts';
import type { Framing } from '~/theme/iridisProjector.ts';

/**
 * Theme lab: proof that the iridis engine drives every Nuxt UI token. The two
 * controls (brand seed + framing) feed the projector; the components below are
 * plain Nuxt UI and recolor entirely from the engine-written CSS variables.
 */
const seed = ref<string>('#7c3aed');
const framing = ref<Framing>('dark');
const applying = ref<boolean>(false);

async function reproject(): Promise<void> {
  applying.value = true;
  try {
    await applyIridisTheme([seed.value], framing.value);
  } finally {
    applying.value = false;
  }
}

onMounted(reproject);
watch([seed, framing], reproject);

const snippet = `const state = await engine.run({
  colors:  ['${'${seed}'}'],
  roles:   iridisNuxtSchema,
  runtime: { framing: '${'${framing}'}', colorSpace: 'srgb' },
});
// state.roles -> --ui-color-primary-50..950, --ui-bg, --ui-text ...`;
</script>

<template>
  <UContainer class="py-10 space-y-8">
    <div class="space-y-2">
      <h1 class="text-3xl font-bold text-highlighted">iridis × Nuxt UI</h1>
      <p class="text-muted">
        Every color on this page is generated by <code>engine.run()</code>. Change the brand
        seed or framing and the whole Nuxt UI component set re-tones from the engine output.
      </p>
    </div>

    <UCard>
      <div class="flex flex-wrap items-center gap-6">
        <label class="flex items-center gap-2 text-sm">
          <span class="text-muted">Brand seed</span>
          <input v-model="seed" type="color" class="h-8 w-12 cursor-pointer rounded border border-default bg-transparent" >
          <span class="font-mono text-xs">{{ seed }}</span>
        </label>
        <USwitch
          :model-value="framing === 'dark'"
          label="Dark framing"
          @update:model-value="framing = $event ? 'dark' : 'light'"
        />
        <UBadge v-if="applying" color="neutral" variant="soft">projecting…</UBadge>
      </div>
    </UCard>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold text-highlighted">Buttons</h2>
      <div class="flex flex-wrap gap-3">
        <UButton color="primary">Primary</UButton>
        <UButton color="primary" variant="outline">Outline</UButton>
        <UButton color="primary" variant="soft">Soft</UButton>
        <UButton color="secondary">Secondary</UButton>
        <UButton color="success">Success</UButton>
        <UButton color="warning">Warning</UButton>
        <UButton color="error">Error</UButton>
        <UButton color="info">Info</UButton>
        <UButton color="neutral" variant="outline">Neutral</UButton>
      </div>
    </section>

    <section class="grid gap-4 sm:grid-cols-2">
      <UCard>
        <template #header><span class="font-semibold">Form controls</span></template>
        <div class="space-y-4">
          <UInput placeholder="Search…" icon="i-lucide-search" />
          <USlider :default-value="60" />
          <div class="flex gap-2">
            <UBadge color="primary">primary</UBadge>
            <UBadge color="success" variant="soft">success</UBadge>
            <UBadge color="error" variant="outline">error</UBadge>
          </div>
        </div>
      </UCard>
      <UCard>
        <template #header><span class="font-semibold">The call behind it</span></template>
        <pre class="overflow-x-auto rounded bg-elevated p-3 text-xs"><code>{{ snippet }}</code></pre>
      </UCard>
    </section>

    <section class="space-y-3">
      <h2 class="text-lg font-semibold text-highlighted">Primary scale (engine-generated)</h2>
      <div class="flex flex-wrap gap-1">
        <div
          v-for="s in [50,100,200,300,400,500,600,700,800,900,950]"
          :key="s"
          class="h-10 w-10 rounded"
          :style="{ backgroundColor: `var(--ui-color-primary-${s})` }"
          :title="`primary-${s}`"
        />
      </div>
    </section>
  </UContainer>
</template>
