import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { pathToFileURL } from 'node:url';

import { GenerateDefaultTheme } from '../app/build/GenerateDefaultTheme.ts';
import { DefaultThemeCss } from '../app/theme/DefaultThemeCss.ts';

await test('default theme CSS is deterministic and contains both framing selectors', () => {
  const css = DefaultThemeCss.generate();
  const blocks = css.split('\n');

  assert.equal(css, DefaultThemeCss.generate());
  assert.equal(blocks.length, 2);
  assert.equal(blocks[0]?.startsWith('html:root, html:root:not(.dark) {'), true);
  assert.equal(blocks[1]?.startsWith('html:root.dark {'), true);
  assert.notEqual(blocks[0], blocks[1]);
  assert.equal(css.includes('--ui-bg:#'), true);
  assert.equal(css.includes('--ui-color-primary-500:#'), true);
  assert.equal(css.includes('undefined'), false);
});

await test('default theme writer preserves generated bytes at an explicit destination', (context) => {
  const directory = mkdtempSync(join(tmpdir(), 'iridis-default-theme-'));
  context.after(() => {rmSync(directory, { 'force': true, 'recursive': true });});
  const destination = pathToFileURL(join(directory, 'theme-default.css'));

  GenerateDefaultTheme.run(destination);

  assert.equal(readFileSync(destination, 'utf8'), DefaultThemeCss.generate());
});
