/**
 * iridis resolved-roles → Nuxt UI token mapping.
 *
 * The engine (owned by `useIridis`) resolves a role palette; this module maps
 * those resolved roles onto Nuxt UI v4's CSS variables so the whole component
 * library is themed by the engine. Semantic colors come from REAL resolved roles
 * (brand, accent-alt, success, warning, error, info) rather than fixed hues, so
 * the demonstration is honest: every token is engine output.
 *
 * Each `--ui-color-{alias}-{50..950}` scale is generated by holding the resolved
 * role's OKLCH chroma + hue and stepping perceptual lightness across a fixed
 * target array; `oklchToRgb` gamut-maps every step to a valid sRGB hex.
 */

import { oklchToRgb } from '@studnicky/iridis';

export type Framing = 'dark' | 'light';

export interface ResolvedRole {
  readonly hex: string;
  readonly oklch: { readonly l: number; readonly c: number; readonly h: number };
}

export type ResolvedRoles = Record<string, ResolvedRole>;

const SHADE_KEYS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
const L_TARGETS_LIGHT = [0.985, 0.955, 0.915, 0.855, 0.775, 0.685, 0.595, 0.505, 0.415, 0.335, 0.255];
const L_TARGETS_DARK  = [0.985, 0.945, 0.885, 0.805, 0.715, 0.635, 0.555, 0.475, 0.395, 0.315, 0.235];

/**
 * Canonical hues (OKLCH degrees) for status aliases. iridis resolves the
 * `success`/`warning`/`error` ROLES by lightness/chroma envelope, not by hue, so
 * mapping the role directly can yield a magenta "success". Instead the status
 * scales use fixed semantic hues but inherit the palette's chroma, so they stay
 * green/amber/red/blue while re-toning with the brand. Structural aliases
 * (primary/secondary/neutral) do come from the resolved brand.
 */
const STATUS_HUE: Record<string, number> = {
  'success': 150,
  'warning':  80,
  'error':    27,
  'info':    250,
};

/** iridis role name → Nuxt UI derived shortcut variable. */
const SHORTCUT_MAP: ReadonlyArray<readonly [string, string]> = [
  ['background', '--ui-bg'],
  ['bg-soft', '--ui-bg-muted'],
  ['surface', '--ui-bg-elevated'],
  ['text', '--ui-text'],
  ['text-strong', '--ui-text-highlighted'],
  ['text-subtle', '--ui-text-muted'],
  ['muted', '--ui-text-dimmed'],
  ['border', '--ui-border'],
  ['border-strong', '--ui-border-accented'],
  ['brand', '--ui-primary'],
];

function ramp(chroma: number, hue: number, framing: Framing): Record<number, string> {
  const targets = framing === 'dark' ? L_TARGETS_DARK : L_TARGETS_LIGHT;
  const out: Record<number, string> = {};
  for (let i = 0; i < SHADE_KEYS.length; i += 1) {
    const t = targets[i] as number;
    const edge = Math.min(t, 1 - t) / 0.5;
    const c = chroma * (0.35 + 0.65 * edge);
    out[SHADE_KEYS[i] as number] = oklchToRgb.apply(t, c, hue).hex;
  }
  return out;
}

/**
 * Pure mapping: resolved roles → Nuxt UI CSS variable map. No DOM access, so it
 * is unit-testable. Falls back to the brand hue for any semantic role the active
 * schema does not resolve, and derives neutral from the muted/text axis.
 */
export function mapRolesToTokens(roles: ResolvedRoles, framing: Framing): Record<string, string> {
  const brand = roles['brand'];
  if (!brand) throw new Error('iridis projector: schema did not resolve a brand role');
  const tokens: Record<string, string> = {};

  const writeScale = (alias: string, ok: { c: number; h: number }): void => {
    const scale = ramp(ok.c, ok.h, framing);
    for (const key of SHADE_KEYS) tokens[`--ui-color-${alias}-${key}`] = scale[key] as string;
  };

  const brandChroma = brand.oklch.c;
  /* structural aliases follow the resolved brand. */
  writeScale('primary', brand.oklch);
  writeScale('secondary', { 'c': brandChroma, 'h': (brand.oklch.h + 150) % 360 });
  /* status aliases: canonical hue, palette-derived chroma. */
  for (const alias of Object.keys(STATUS_HUE)) {
    writeScale(alias, { 'c': Math.max(0.10, brandChroma * 0.9), 'h': STATUS_HUE[alias] as number });
  }
  /* neutral: brand hue at near-zero chroma. */
  writeScale('neutral', { 'c': 0.008, 'h': brand.oklch.h });

  for (const [role, cssVar] of SHORTCUT_MAP) {
    const r = roles[role];
    if (r) tokens[cssVar] = r.hex;
  }
  if (!tokens['--ui-border-muted']) tokens['--ui-border-muted'] = roles['divider']?.hex ?? roles['border']?.hex ?? brand.hex;

  return tokens;
}

/** DOM writer. SSR-guarded; call only in the browser. */
export function applyTokens(tokens: Record<string, string>, framing: Framing): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  for (const [k, v] of Object.entries(tokens)) root.style.setProperty(k, v);
  root.classList.toggle('dark', framing === 'dark');
  root.dataset['iridisFraming'] = framing;
}
