/**
 * iridis → Nuxt UI token projector.
 *
 * This is the core of the whole site: every color token Nuxt UI renders is
 * produced by the iridis engine, not by Tailwind's default palette. The engine
 * resolves a role palette from the seed colors; this module maps those resolved
 * roles onto Nuxt UI v4's CSS variables and writes them to the document root.
 *
 * Nuxt UI v4 exposes its palette as CSS variables:
 *   - `--ui-color-{alias}-{50..950}` scales for aliases primary/secondary/
 *     success/info/warning/error/neutral
 *   - derived shortcuts `--ui-bg`, `--ui-bg-muted`, `--ui-bg-elevated`,
 *     `--ui-text`, `--ui-text-muted`, `--ui-border`, `--ui-primary`
 * All are runtime-overridable via `documentElement.style.setProperty`, so the
 * engine can drive the entire component library live.
 *
 * Shade-ramp method: each 11-step 50→950 scale is generated by holding the
 * source color's OKLCH chroma + hue and stepping perceptual lightness across a
 * fixed target array (light → dark). OKLCH lightness is perceptually uniform, so
 * a linear L ramp yields evenly-spaced shades. `oklchToRgb` gamut-maps each step
 * back to a valid sRGB hex. Primary follows the resolved brand hue; the semantic
 * aliases use canonical hues but inherit the brand's chroma, so the whole system
 * re-tones when the brand seed changes while keeping success green, error red,
 * etc. Neutral is the brand hue at near-zero chroma.
 */

import { Engine, coreTasks, oklchToRgb } from '@studnicky/iridis';
import { contrastPlugin } from '@studnicky/iridis-contrast';
import type { RoleSchemaInterface } from '@studnicky/iridis/types';

export type Framing = 'dark' | 'light';

/** Perceptual OKLCH lightness targets for shades 50 → 950 (light → dark). */
const SHADE_KEYS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
const L_TARGETS_LIGHT = [0.985, 0.955, 0.915, 0.855, 0.775, 0.685, 0.595, 0.505, 0.415, 0.335, 0.255];
const L_TARGETS_DARK  = [0.985, 0.945, 0.885, 0.805, 0.715, 0.635, 0.555, 0.475, 0.395, 0.315, 0.235];

/** Canonical hues for the semantic aliases (OKLCH degrees). */
const SEMANTIC_HUE: Record<string, number> = {
  'success': 150,
  'info':    250,
  'warning':  80,
  'error':    27,
};

/** Compact role schema (dark + light) resolving the anchors the projector needs. */
const SCHEMA: Record<Framing, RoleSchemaInterface> = {
  'dark': {
    'name':        'iridis-nuxt-dark',
    'description': 'Nuxt UI anchor roles, dark framing.',
    'roles': [
      { 'name': 'background', 'intent': 'background', 'required': true, 'lightnessRange': [0.04, 0.14], 'chromaRange': [0.00, 0.04] },
      { 'name': 'surface',    'intent': 'background', 'required': true, 'derivedFrom': 'background', 'lightnessRange': [0.08, 0.18], 'chromaRange': [0.00, 0.06] },
      { 'name': 'text',       'intent': 'text',       'required': true, 'lightnessRange': [0.85, 0.96], 'chromaRange': [0.00, 0.04] },
      { 'name': 'muted',      'intent': 'muted',                        'lightnessRange': [0.50, 0.68], 'chromaRange': [0.00, 0.06] },
      { 'name': 'brand',      'intent': 'accent',     'required': true, 'lightnessRange': [0.55, 0.78], 'chromaRange': [0.12, 0.30] },
    ],
    'contrastPairs': [
      { 'foreground': 'text',  'background': 'background', 'minRatio': 4.5, 'algorithm': 'wcag21' },
      { 'foreground': 'brand', 'background': 'background', 'minRatio': 3.0, 'algorithm': 'wcag21' },
    ],
  },
  'light': {
    'name':        'iridis-nuxt-light',
    'description': 'Nuxt UI anchor roles, light framing.',
    'roles': [
      { 'name': 'background', 'intent': 'background', 'required': true, 'lightnessRange': [0.94, 0.99], 'chromaRange': [0.00, 0.03] },
      { 'name': 'surface',    'intent': 'background', 'required': true, 'derivedFrom': 'background', 'lightnessRange': [0.88, 0.96], 'chromaRange': [0.00, 0.04] },
      { 'name': 'text',       'intent': 'text',       'required': true, 'lightnessRange': [0.10, 0.22], 'chromaRange': [0.00, 0.04] },
      { 'name': 'muted',      'intent': 'muted',                        'lightnessRange': [0.40, 0.55], 'chromaRange': [0.00, 0.06] },
      { 'name': 'brand',      'intent': 'accent',     'required': true, 'lightnessRange': [0.40, 0.58], 'chromaRange': [0.14, 0.32] },
    ],
    'contrastPairs': [
      { 'foreground': 'text',  'background': 'background', 'minRatio': 4.5, 'algorithm': 'wcag21' },
      { 'foreground': 'brand', 'background': 'background', 'minRatio': 3.0, 'algorithm': 'wcag21' },
    ],
  },
};

const PIPELINE = ['intake:hex', 'resolve:roles', 'expand:family', 'enforce:contrast'] as const;

const engine = new Engine();
for (const t of coreTasks) engine.tasks.register(t);
engine.adopt(contrastPlugin);
engine.pipeline([...PIPELINE]);

/** One 11-step scale: hold chroma+hue, step lightness across the target array. */
function ramp(chroma: number, hue: number, framing: Framing): Record<number, string> {
  const targets = framing === 'dark' ? L_TARGETS_DARK : L_TARGETS_LIGHT;
  const out: Record<number, string> = {};
  for (let i = 0; i < SHADE_KEYS.length; i += 1) {
    /* Taper chroma at the extremes so 50/950 don't over-saturate. */
    const t = targets[i] as number;
    const edge = Math.min(t, 1 - t) / 0.5;
    const c = chroma * (0.35 + 0.65 * edge);
    out[SHADE_KEYS[i] as number] = oklchToRgb.apply(t, c, hue).hex;
  }
  return out;
}

/**
 * Pure mapping: seeds + framing → Nuxt UI CSS variable map. No DOM access, so
 * this is unit-testable. Runs the engine, then derives the seven semantic scales
 * plus the bg/text/border shortcuts from the resolved roles.
 */
export async function rolesToNuxtTokens(seeds: string[], framing: Framing): Promise<Record<string, string>> {
  const state = await engine.run({
    'colors':   seeds,
    'roles':    SCHEMA[framing],
    'contrast': { 'level': 'AA', 'algorithm': 'wcag21' },
    'runtime':  { 'framing': framing, 'colorSpace': 'srgb' },
  });

  const roles = state.roles as Record<string, { 'hex': string; 'oklch': { 'l': number; 'c': number; 'h': number } }>;
  const brand = roles['brand'];
  const bg = roles['background'];
  const surface = roles['surface'];
  const text = roles['text'];
  const muted = roles['muted'];
  if (!brand || !bg || !text || !muted) {
    throw new Error('iridis projector: schema did not resolve the required anchor roles');
  }

  const brandChroma = brand.oklch.c;
  const tokens: Record<string, string> = {};

  const writeScale = (alias: string, chroma: number, hue: number): void => {
    const scale = ramp(chroma, hue, framing);
    for (const key of SHADE_KEYS) tokens[`--ui-color-${alias}-${key}`] = scale[key] as string;
  };

  /* primary follows the resolved brand hue + chroma. */
  writeScale('primary', brandChroma, brand.oklch.h);
  /* secondary: brand hue rotated, same chroma character. */
  writeScale('secondary', brandChroma, (brand.oklch.h + 150) % 360);
  /* semantic aliases: canonical hue, brand-derived chroma so the set re-tones. */
  for (const alias of Object.keys(SEMANTIC_HUE)) {
    writeScale(alias, Math.max(0.10, brandChroma * 0.9), SEMANTIC_HUE[alias] as number);
  }
  /* neutral: brand hue at near-zero chroma. */
  writeScale('neutral', 0.008, brand.oklch.h);

  /* Derived shortcuts read straight from the resolved anchor roles. */
  tokens['--ui-primary']      = brand.hex;
  tokens['--ui-bg']           = bg.hex;
  tokens['--ui-bg-elevated']  = surface?.hex ?? bg.hex;
  tokens['--ui-bg-muted']     = surface?.hex ?? bg.hex;
  tokens['--ui-text']         = text.hex;
  tokens['--ui-text-muted']   = muted.hex;
  tokens['--ui-text-dimmed']  = muted.hex;
  tokens['--ui-border']       = muted.hex;
  tokens['--ui-border-muted'] = muted.hex;

  return tokens;
}

/** DOM writer. SSR-guarded; call only in the browser. */
export function applyTokens(tokens: Record<string, string>, framing: Framing): void {
  if (typeof document === 'undefined') return;
  const root = document.documentElement;
  for (const [k, v] of Object.entries(tokens)) root.style.setProperty(k, v);
  root.classList.toggle('dark', framing === 'dark');
  root.dataset['iridisFraming'] = framing;
}

/** Convenience: resolve + apply in one call (browser only). */
export async function applyIridisTheme(seeds: string[], framing: Framing): Promise<void> {
  if (typeof document === 'undefined') return;
  applyTokens(await rolesToNuxtTokens(seeds, framing), framing);
}
